/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atelieryl_wonderdroid_WonderSwan_Header */

#ifndef _Included_com_atelieryl_wonderdroid_WonderSwan_Header
#define _Included_com_atelieryl_wonderdroid_WonderSwan_Header
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
